#!/usr/bin/env python3
"""
ChimerA latency probe — measures gateway latency and attributes it to
browser round-trip vs gateway overhead vs concurrency lock contention.

Stdlib only. Two modes:

  http  : calls POST /v1/chat/completions directly (measures the gateway+browser
          path, plus TTFT when --stream is set).
  anv   : shells out to `anv --no-tui` (measures the full agentic harness path:
          anv system prompt + tool schemas -> ChimerA -> model). With --agentic
          it generates fixture files and forces tool-using multi-round spins,
          then parses ANV_CONTEXT_LEDGER from stdout (rounds, estimated input
          tokens, folds) and the gateway request log (per-round duration,
          status, prompt chars). harness_overhead = spin wall - sum(rounds), so
          the harness cost is separated from browser/model time.

Metrics deltas are scraped from /metrics before and after the run, so wall-clock
is split into browser round-trip and everything else.

Examples:
  python3 scripts/latency_probe.py --n 10
  python3 scripts/latency_probe.py --n 10 --concurrency 4
  python3 scripts/latency_probe.py --n 5 --stream
  python3 scripts/latency_probe.py --mode anv --n 3 --agentic --anv-yolo
  python3 scripts/latency_probe.py --mode anv --n 3 --prompt "Reply with exactly: PONG"
"""
import argparse
import json
import os
import re
import statistics
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request

DEFAULT_PROMPT = "Reply with exactly the word PONG and nothing else."

SCRIPT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_GATEWAY_LOG = os.path.join(SCRIPT_ROOT, "logs", "probe-run.log")

FIXTURE_FILLER = "The quick brown fox jumps over the lazy dog. "
AGENTIC_PROMPT = (
    "Read the files {a} and {b} using your file tools — do not guess. "
    "Then report the exact LINE3 value from each file and which file has more characters."
)


# ── agentic fixtures ──────────────────────────────────────────────────────
def write_fixture(path: str, label: str, token: str, n_chars: int) -> None:
    head = "\n".join([
        f"spin fixture {label}",
        "generated by scripts/latency_probe.py --agentic",
        f"LINE3={token}",
        "",
    ])
    parts = [head]
    size, i = len(head), 0
    while size < n_chars:
        line = f"{i:06d} {FIXTURE_FILLER}\n"
        parts.append(line)
        size += len(line)
        i += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write("".join(parts)[:max(n_chars, len(head))])


# ── gateway log attribution ────────────────────────────────────────────────
POST_RE = re.compile(
    r'"POST [^"]*/v1/chat/completions HTTP/1\.1" '
    r'from \S+ - (?P<code>\d{3}) \S+ in (?P<dur>\S+)$'
)
SEND_RE = re.compile(r"Sending message \(thread=\S+, len=(?P<len>\d+)\)")
REJECT_RE = re.compile(r"Pre-flight reject: prompt (?P<len>\d+) chars exceeds")
LEDGER_RE = re.compile(r"ANV_CONTEXT_LEDGER (?P<json>\{[^\n]*\})")

_DUR_UNITS = {"ns": 1e-9, "us": 1e-6, "µs": 1e-6, "ms": 1e-3,
              "s": 1.0, "m": 60.0, "h": 3600.0}


def parse_go_duration(s: str) -> float:
    """Go time.Duration string -> seconds (handles '1m8.5s', '420.9µs')."""
    total = 0.0
    for v, u in re.findall(r"(\d+(?:\.\d+)?)(ns|us|µs|ms|s|m|h)", s):
        total += float(v) * _DUR_UNITS[u]
    return total


def read_from(path: str, offset: int):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            f.seek(offset)
            return f.read(), os.path.getsize(path)
    except OSError:
        return "", offset


def parse_rounds(text: str) -> list:
    """One gateway-log slice -> [{code, wall, chars}] per chat completion."""
    rounds, pending = [], None
    for line in text.splitlines():
        m = SEND_RE.search(line) or REJECT_RE.search(line)
        if m:
            pending = int(m.group("len"))
            continue
        m = POST_RE.search(line)
        if m:
            rounds.append({
                "code": int(m.group("code")),
                "wall": parse_go_duration(m.group("dur")),
                "chars": pending,
            })
            pending = None
    return rounds


def parse_ledger(out: str):
    m = LEDGER_RE.search(out)
    if not m:
        return None
    try:
        return json.loads(m.group("json"))
    except json.JSONDecodeError:
        return None


# ── provider refresh ───────────────────────────────────────────────────────
def post_refresh(args):
    """Reset the provider conversation. Returns (seconds, error-or-None)."""
    try:
        req = urllib.request.Request(
            root_of(args.base_url) + "/v1/refresh", data=b"{}",
            headers={"Content-Type": "application/json",
                     "Authorization": f"Bearer {args.token}"}, method="POST")
        t0 = time.perf_counter()
        with urllib.request.urlopen(req, timeout=120) as r:
            r.read()
        return time.perf_counter() - t0, None
    except Exception as e:  # noqa: BLE001
        return 0.0, f"{type(e).__name__}: {e}"


# ── metrics ────────────────────────────────────────────────────────────────
def root_of(base_url: str) -> str:
    return re.sub(r"/v1/?$", "", base_url.rstrip("/"))


def scrape(url: str, headers: dict, timeout: float = 5.0) -> dict:
    """Return {metric_name: {label_str: value}} for chimera_* counters/gauges."""
    out: dict = {}
    try:
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=timeout) as r:
            body = r.read().decode("utf-8", "replace")
    except Exception:
        return out
    val_re = re.compile(r"^([a-zA-Z_:][a-zA-Z0-9_:]*)(\{[^}]*\})?\s+([0-9eE.+-]+)$")
    for line in body.splitlines():
        if not line.startswith("chimera_"):
            continue
        m = val_re.match(line.strip())
        if not m:
            continue
        name, labels, val = m.group(1), m.group(2) or "", m.group(3)
        try:
            out.setdefault(name, {})[labels] = float(val)
        except ValueError:
            pass
    return out


def delta(after: dict, before: dict, name: str) -> dict:
    """Per-label difference for a metric name."""
    res = {}
    for label, v in after.get(name, {}).items():
        d = v - before.get(name, {}).get(label, 0.0)
        if d:
            res[label] = d
    return res


# ── stats ──────────────────────────────────────────────────────────────────
def pct(xs, p):
    if not xs:
        return float("nan")
    s = sorted(xs)
    k = max(0, min(len(s) - 1, int(round((p / 100.0) * (len(s) - 1)))))
    return s[k]


def fmt(x):
    return "n/a" if x != x else f"{x:.2f}s"


# ── http mode ──────────────────────────────────────────────────────────────
def one_http(args, results, idx):
    url = args.base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": args.model,
        "messages": [{"role": "user", "content": args.prompt}],
        "stream": bool(args.stream),
    }
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {args.token}",
    }
    body = json.dumps(payload).encode()
    t0 = time.perf_counter()
    ttft = None
    err = None
    nbytes = 0
    try:
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=args.timeout) as r:
            if args.stream:
                # ChimerA emits an empty "role" chunk immediately, then blocks on
                # the browser round trip, then replays the text in 20-char chunks.
                # So the honest metric is time-to-first-CONTENT, not time to first byte.
                while True:
                    chunk = r.readline()
                    if not chunk:
                        break
                    nbytes += len(chunk)
                    if ttft is None and b"content" in chunk:
                        s = chunk.decode("utf-8", "replace").strip()
                        if s.startswith("data:"):
                            s = s[5:].strip()
                        if s and s != "[DONE]":
                            try:
                                obj = json.loads(s)
                                delta = (obj.get("choices") or [{}])[0].get("delta") or {}
                                if delta.get("content"):
                                    ttft = time.perf_counter() - t0
                            except Exception:  # noqa: BLE001
                                pass
            else:
                nbytes = len(r.read())
    except urllib.error.HTTPError as e:
        err = f"HTTP {e.code}: {e.read().decode('utf-8', 'replace')[:200]}"
    except Exception as e:  # noqa: BLE001 — probe reports whatever happened
        err = f"{type(e).__name__}: {e}"
    wall = time.perf_counter() - t0
    results[idx] = {"idx": idx, "wall": wall, "ttft": ttft, "err": err, "bytes": nbytes}


# ── anv mode ───────────────────────────────────────────────────────────────
def one_anv(args, results, idx):
    env = dict(os.environ)
    env[args.api_key_env] = args.token
    cmd = ["anv", "--no-tui"]
    if getattr(args, "anv_yolo", False):
        cmd.append("--yolo")
    cmd += ["-p", args.provider, "-m", args.model, args.prompt]
    refresh_s, refresh_err = (None, None)
    if getattr(args, "refresh_each", False):
        # The browser conversation is sticky across requests, so a spin would
        # otherwise inherit the previous spin's reads. Reset outside the timer.
        refresh_s, refresh_err = post_refresh(args)
    log_path = args.gateway_log if args.gateway_log and os.path.exists(args.gateway_log) else None
    offset = os.path.getsize(log_path) if log_path else 0
    t0 = time.perf_counter()
    err = None
    out = ""
    rc = None
    try:
        p = subprocess.run(
            cmd, env=env, capture_output=True, text=True, timeout=args.timeout,
            cwd=SCRIPT_ROOT, stdin=subprocess.DEVNULL,
        )
        rc = p.returncode
        out = (p.stdout or "") + (p.stderr or "")
        if rc != 0:
            err = f"rc={rc}: " + " ".join(out.split())[:200]
    except subprocess.TimeoutExpired:
        err = f"timeout after {args.timeout}s"
    except Exception as e:  # noqa: BLE001
        err = f"{type(e).__name__}: {e}"
    wall = time.perf_counter() - t0

    ledger = parse_ledger(out)
    rounds = []
    if log_path and args.concurrency == 1:
        # The POST line is written after anv has the response, but give the
        # gateway a moment to flush the last one before reading.
        expect = (ledger or {}).get("rounds") or 0
        deadline = time.time() + 2.0
        while True:
            text, _ = read_from(log_path, offset)
            rounds = parse_rounds(text)
            if len(rounds) >= expect or time.time() > deadline:
                break
            time.sleep(0.1)

    toks = getattr(args, "fixture_tokens", None)
    results[idx] = {
        "idx": idx, "wall": wall, "ttft": None, "err": err, "bytes": len(out),
        "rc": rc, "rounds": (ledger or {}).get("rounds"), "ledger": ledger,
        "round_times": rounds, "answer": LEDGER_RE.sub("", out).strip()[-400:],
        "verified": all(t in out for t in toks) if toks else None,
        "refresh_s": refresh_s, "refresh_err": refresh_err,
    }


# ── runner ─────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description="ChimerA latency probe")
    ap.add_argument("--base-url", default=os.environ.get("CHIMERA_BASE_URL", "http://localhost:8000/v1"))
    ap.add_argument("--token", default=os.environ.get("CHIMERA_API_KEY", "chimera"))
    ap.add_argument("--api-key-env", default="CHIMERA_API_KEY", help="env var name anv reads (anv mode)")
    ap.add_argument("--provider", default="chimera", help="anv provider name (anv mode)")
    ap.add_argument("--model", default="chimera-qwen")
    ap.add_argument("--mode", choices=["http", "anv"], default="http")
    ap.add_argument("--n", type=int, default=5, help="total requests")
    ap.add_argument("--concurrency", type=int, default=1)
    ap.add_argument("--stream", action="store_true", help="measure TTFT (http mode)")
    ap.add_argument("--prompt", default=DEFAULT_PROMPT)
    ap.add_argument("--agentic", action="store_true",
                    help="anv mode: generate fixtures and force tool-using multi-round spins")
    ap.add_argument("--fixture-chars", type=int, default=6000,
                    help="approximate chars per generated fixture (--agentic)")
    ap.add_argument("--fixture-dir", default=os.path.join(SCRIPT_ROOT, "logs", "spin-fixtures"))
    ap.add_argument("--gateway-log", default=DEFAULT_GATEWAY_LOG,
                    help="gateway stdout log for per-round attribution ('' disables)")
    ap.add_argument("--refresh", action="store_true",
                    help="POST /v1/refresh before measuring (stale-DOM recovery)")
    ap.add_argument("--refresh-each", action="store_true",
                    help="anv mode: refresh before every spin so browser context doesn't leak")
    ap.add_argument("--anv-yolo", action="store_true",
                    help="anv mode: pass --yolo (auto-approve tool calls)")
    ap.add_argument("--timeout", type=float, default=300.0)
    ap.add_argument("--json", metavar="PATH", help="also write raw results as JSON")
    args = ap.parse_args()

    if args.agentic:
        if args.mode != "anv":
            ap.error("--agentic requires --mode anv")
        os.makedirs(args.fixture_dir, exist_ok=True)
        tok_a, tok_b = os.urandom(4).hex(), os.urandom(4).hex()
        fix_a = os.path.join(args.fixture_dir, "spin-a.txt")
        fix_b = os.path.join(args.fixture_dir, "spin-b.txt")
        write_fixture(fix_a, "A", tok_a, args.fixture_chars)
        write_fixture(fix_b, "B", tok_b, args.fixture_chars)
        args.prompt = AGENTIC_PROMPT.format(
            a=os.path.relpath(fix_a, SCRIPT_ROOT), b=os.path.relpath(fix_b, SCRIPT_ROOT))
        args.fixture_tokens = (tok_a, tok_b)

    headers = {"Authorization": f"Bearer {args.token}"}
    metrics_url = root_of(args.base_url) + "/metrics"

    refresh_note = ""
    if args.refresh_each:
        if args.mode != "anv" or args.concurrency != 1:
            ap.error("--refresh-each requires --mode anv and --concurrency 1")
        refresh_note += "  refresh-each=on"
    if args.refresh:
        secs, rerr = post_refresh(args)
        if rerr:
            refresh_note = "  refresh=FAILED"
            print(f"  warn: refresh failed: {rerr}")
        else:
            refresh_note = f"  refresh={secs:.1f}s"

    print(f"ChimerA latency probe")
    print(f"  target : {args.base_url}  model={args.model}  mode={args.mode}"
          f"{'  stream=on' if args.stream else ''}"
          f"{'  agentic=on' if args.agentic else ''}{refresh_note}")
    print(f"  load   : n={args.n}  concurrency={args.concurrency}")
    print(f"  prompt : {args.prompt[:70]!r} ({len(args.prompt)} chars)")
    print()

    before = scrape(metrics_url, headers)
    t_start = time.perf_counter()

    results = [None] * args.n
    sem = threading.Semaphore(args.concurrency)
    worker = one_anv if args.mode == "anv" else one_http

    def run(i):
        with sem:
            worker(args, results, i)

    threads = [threading.Thread(target=run, args=(i,)) for i in range(args.n)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    elapsed = time.perf_counter() - t_start

    after = scrape(metrics_url, headers)

    ok = [r for r in results if r and not r["err"]]
    bad = [r for r in results if r and r["err"]]
    walls = [r["wall"] for r in ok]
    ttfts = [r["ttft"] for r in ok if r["ttft"] is not None]

    print(f"  result : ok {len(ok)}/{args.n}  errors {len(bad)}   (run wall {elapsed:.2f}s)")
    if walls:
        print(f"  wall   : p50={fmt(pct(walls,50))}  p95={fmt(pct(walls,95))}  "
              f"min={fmt(min(walls))}  max={fmt(max(walls))}  mean={fmt(statistics.mean(walls))}")
    if ttfts:
        print(f"  ttfc   : p50={fmt(pct(ttfts,50))}  p95={fmt(pct(ttfts,95))}  "
              f"mean={fmt(statistics.mean(ttfts))}   ({len(ttfts)} samples)")
        print(f"           (time-to-first-CONTENT; ChimerA streams after the full "
              f"browser turn, so this ~= total latency)")
    if bad:
        print("  errors :")
        for r in bad[:5]:
            print(f"    - {r['err']}")
        if len(bad) > 5:
            print(f"    ... {len(bad)-5} more")

    # ── agentic spin breakdown (anv mode) ──────────────────────────────────
    if args.mode == "anv" and any(r and r.get("ledger") for r in results):
        print()
        print("  agentic spins:")
        all_rounds = []
        for r in results:
            if not r:
                continue
            led = r.get("ledger") or {}
            rts = r.get("round_times") or []
            all_rounds.extend(rts)
            rsum = sum(x["wall"] for x in rts)
            overhead = r["wall"] - rsum if rts else float("nan")
            verified = ""
            if r.get("verified") is not None:
                verified = f"  verified={'yes' if r['verified'] else 'NO'}"
            est = led.get("estimated_input_total")
            est = f"{est}t" if est is not None else "n/a"
            refresh = ""
            if r.get("refresh_s") is not None:
                refresh = f" pre_refresh={r['refresh_s']:.1f}s"
            print(f"    spin {r['idx']}: wall={r['wall']:.1f}s rc={r.get('rc')} "
                  f"rounds={r.get('rounds')} est_in={est} "
                  f"artifacts={led.get('artifacts_created', '-')} "
                  f"folds={led.get('meso_folds', '-')} "
                  f"harness_overhead={fmt(overhead)}{verified}{refresh}")
            if rts:
                pieces = []
                for x in rts:
                    p = f" p={x['chars']}" if x.get("chars") else ""
                    pieces.append(f"[{x['code']} {x['wall']:.1f}s{p}]")
                if r.get("err"):
                    pieces.append(f"(err: {r['err'][:60]})")
                print(f"              {' '.join(pieces)}")
        if all_rounds:
            durs = [x["wall"] for x in all_rounds]
            codes = {}
            for x in all_rounds:
                codes[x["code"]] = codes.get(x["code"], 0) + 1
            print(f"    rounds : n={len(durs)}  p50={fmt(pct(durs,50))}  "
                  f"p95={fmt(pct(durs,95))}  mean={fmt(statistics.mean(durs))}  codes={codes}")

    # ── attribution ────────────────────────────────────────────────────────
    d_req = delta(after, before, "chimera_chat_requests_total")
    d_dur = delta(after, before, "chimera_response_duration_seconds_sum")
    d_dur_n = delta(after, before, "chimera_response_duration_seconds_count")
    d_lock = delta(after, before, "chimera_lock_wait_seconds_sum")
    d_lock_n = delta(after, before, "chimera_lock_wait_seconds_count")
    fb = delta(after, before, "chimera_selector_fallback_total")

    if d_req or d_dur:
        print()
        print("  attribution (from /metrics delta):")
        codes = {}
        for label, v in d_req.items():
            m = re.search(r'code="([^"]*)"', label)
            codes[m.group(1) if m else label] = int(v)
        if codes:
            print(f"    chat requests by code : {codes}")
        br_sum = sum(d_dur.values())
        br_n = sum(d_dur_n.values())
        if br_n:
            print(f"    browser round-trip    : n={int(br_n)}  sum={br_sum:.2f}s  mean={br_sum/br_n:.2f}s")
            if walls and args.mode != "anv":
                print(f"    gateway overhead      : mean={statistics.mean(walls) - br_sum/br_n:.2f}s"
                      f"  (wall mean - browser mean)")
            elif args.mode == "anv" and ok:
                # Per-spin overhead is printed above; aggregating wall mean vs
                # round mean here would mix units when spins have different
                # round counts.
                ovs = []
                for r in ok:
                    rsum = sum(x["wall"] for x in (r.get("round_times") or []))
                    if r.get("round_times"):
                        ovs.append(r["wall"] - rsum)
                if ovs:
                    print(f"    harness overhead      : mean={statistics.mean(ovs):.2f}s"
                          f"  (spin wall - sum of its rounds)")
        if d_lock_n:
            lk = sum(d_lock.values()) / sum(d_lock_n.values())
            print(f"    lock wait (contention) : n={int(sum(d_lock_n.values()))}  mean={lk:.3f}s")
        if fb:
            print(f"    !! selector fallbacks  : {fb}   (vendor UI drift)")

    if args.json:
        with open(args.json, "w") as f:
            json.dump({"args": vars(args), "results": results,
                       "metrics_delta": {"requests": d_req, "browser_sum": d_dur}}, f, indent=2)
        print(f"\n  raw results -> {args.json}")

    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
